### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by rvanlaar** [jethrogb/nvme-ata-security#1]
Please add a few lines on how to run this program.

i.e. Do I need to compile it? and if so, how?

**Comment by jethrogb** [comment]
You need to compile the user utility. After you've [installed Rust](https://www.rust-lang.org/tools/install), you can run `cargo build`.

If you want to run it on boot, and you use mkinitcpio, you need to put the supplied files in the right place. If you use another system to build your initial RAM disk, you'll need to write your own hooks.
