### ISSUE TITLE
Can't unlock disk

### ISSUE THREAD

**Issue by rvanlaar** [jethrogb/nvme-ata-security#4]
I can run query just fine: 
> sudo ./nvme-ata-security query /dev/nvme1n1

> vid:ssvid: 144d:144d
model: S4EMNF0M700990      
serial: SAMSUNG XXXXX              
firmware: 3L2QEXF7
oacs: SECURITY | FORMAT | FIRMWARE | RESERVED1
protocols: [Info, Tcg(1), Tcg(2), AtaSecurity]
ata security: erase time: 1 enhanced erase time: 1, master pwd id: 0140 maxset: false
s_suprt: true s_enabld: true locked: true frozen: false pwcntex: true en_er_sup: true

Running unlock throws an error:
> sudo ./nvme-ata-security unlock -u /dev/nvme1n1

>Performing SECURITY UNLOCK...
Please enter password for SAMSUNG XXXXX S4EMNF0M700990:
There was an error executing the command: Nvme(InvalidFieldInCommand)

What is going on?

**Comment by jethrogb** [comment]
Are you using the right password? Did you configure the password using `nvme-ata-security`? In the [current code](https://github.com/jethrogb/nvme-ata-security/blob/2cb4f7877e82d530e7bc3a3a3adf0147a09bfd63/user/src/main.rs#L362-L368), the password supplied to the drive is `SHA256(password entry || model number || serial number)`

**Comment by rvanlaar** [comment]
That would explain a lot. I configured the password using the bios.

**Comment by rvanlaar** [comment]
What would be an easy way to override this?
And send the password directly to the nvme command?

**Comment by jethrogb** [comment]
You can modify the source to do whatever you want.

**Comment by rvanlaar** [comment]
Thanks, my rust is a bit rusty though. There seems to be a right incantation to the security commands. I'm also trying with nvme security-send. How did you figure out what code to write to make it work?

**Comment by rvanlaar** [comment]
I've taking the hash output from: https://github.com/jethrogb/lenovo-password
and used that as the final password in this program. 

That didn't work. My guess is that lenovo changed their algorithm, so closing this issue.
